name=CCARemote
version=1.0.0
author=HTL Anichstrasse
maintainer=Andreas Eckhart
sentence=BLE und WiFi Steuerung für den ESP32 (CCA Remote)
paragraph=Flexible Steuerung von Mikrocontrollern über Bluetooth Low Energy (BLE) oder WLAN (WiFi). Hierfür wird die App \"CCA Remote\" benötigt.
category=Communication
url=https://github.com/andreas-eckhart/CCARemote-Arduino
architectures=esp32
depends=PubSubClient
includes=CCARemote.h