name=CCARemote
version=1.0.0
author=HTL Anichstrasse
maintainer=Andreas Eckhart
sentence=ESP32, ESP8266 & Arduino Dashboard: Flexible Steuerung per BLE & WLAN
paragraph=Flexible Steuerung von Mikrocontrollern über Bluetooth LE oder WiFi (ESP32, ESP8266, Arduino Uno/Nano + HM-10). Hierfür wird die App \"CCA Remote\" benötigt (Android / iOS).
category=Communication
url=https://github.com/andreas-eckhart/CCARemote-Arduino
architectures=*
depends=PubSubClient
includes=CCARemote.h